services:
   postgres:
      image: postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: bitcoinmonitor
      ports:
         - "5432:5432"

   pgadmin:
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: admin
      ports:
         - "5050:80"

   app:
      build: .
      ports:
         - "8080:8080"
      environment:
         - DB_URL=postgres://postgres:postgres@postgres:5432/bitcoinmonitor?sslmode=disable
         - APP_PORT=8080
         - APP_HOST=0.0.0.0
      depends_on:
         - postgres
